### PR TITLE
Merge env into prepared session

### LINKED ISSUE #25: REQUESTS_CA_BUNDLE not working
In our corporate environment, we are behind a proxy that does SSL interceptions (man in the middle), and it has a custom CA Cert that needs to be used. Normally I just import this CA into the system CA bundle, then tell python requests to use it with the REQUESTS_CA_BUNDLE environment variable and everything works fine. However, it looks like there is an issue in the `upstream.py` with the prepared requests, specifically see this section in the docs for [prepared requests](https://requests.readthedocs.io/en/latest/user/advanced/#prepared-requests):
> When you are using the prepared request flow, keep in mind that it does not take into account the environment. This can cause problems if you are using environment variables to change the behaviour of requests. For example: Self-signed SSL certificates specified in REQUESTS_CA_BUNDLE will not be taken into account. As a result an SSL: CERTIFICATE_VERIFY_FAILED is thrown. You can get around this behaviour by explicitly merging the environment settings into your session.

I have tested this out by replacing the two `s.send` calls in `upstream.py` with the environment merging as shown in the documentation, and it works fine. Fixing that will enable a lot of us that are stuck behind our terrible corporate proxies.

### PR DESCRIPTION
**Pull request by jcox10**
Closes #25. Merge environment into prepared session as discussed in the [requests documentation](https://requests.readthedocs.io/en/latest/user/advanced/#prepared-requests)

### CODE REVIEW

**Comment by jcox10** [comment]
Ok I tested these changes out in my environment and it still works as expected! Thank you for working on this, since Jfrog has refused to do anything.

**Comment by briantist** [comment]
Excellent! The only other thing that's needed is a changelog fragment. I'm sorry I don't have documentation on this but you can see other fragments in `changelogs/archive/`. In this case, make a new file in `changelogs/fragments/` with a name like `25-requests-environment.yml`.

Here's a sample you could use directly or modify it as you see fit:

```yaml
---
minor_changes:
  - upstream proxying - merge the ``requests`` environment for proxied requests so that environment variables such as ``REQUESTS_CA_BUNDLE`` are used appropriately (https://github.com/briantist/galactory/issues/25).
```

**Comment by jcox10** [comment]
@briantist Ok I added the change log as you suggested!

**Review by briantist — APPROVED** [review]

**Comment by briantist** [comment]
@jcox10 thanks a lot for this contribution!

**Pull request merged**
